---
stress_app_install_dir: "/home/{{ stress_app_user }}/stress-app"
stress_app_service_name: stress-app
stress_app_port: 5000
stress_app_user: "{{ ansible_user | default('azureuser') }}"
appinsights_connection_string: ""
